name: av_player
description: A Flutter plugin to play audio and video media
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.okellogerald.av_player
        pluginClass: AvPlayerPlugin
      ios:
        pluginClass: AvPlayerPlugin
